name: Resilience
favicon: null
layout_spectrum: 0.49491
typography_spectrum: 0.56189
title: Resilience Magazine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1d1d1'
    - '#737373'
    - '#9e9e9e'
    - '#b5b5b5'
    - '#535353'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
