name: Resilience
favicon: null
layout_spectrum: 0.35768
typography_spectrum: 0.56189
title: Resilience Magazine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffb3ba'
    - '#ffdfba'
    - '#baffc9'
    - '#bae1ff'
    - '#ffffba'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
