name: Resilience
favicon: null
layout_spectrum: 0.35768
typography_spectrum: 0.56189
title: Resilience Magazine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8b6bf'
    - '#c9d8c5'
    - '#7d4627'
    - '#927e73'
    - '#fdf8ed'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
