name: Resilience
favicon: null
layout_spectrum: 0.49491
typography_spectrum: 0.56189
title: Resilience Magazine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#90877c'
    - '#aba192'
    - '#ecdcc7'
    - '#f6e8d6'
    - '#cec0af'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
