name: Resilience
favicon: null
layout_spectrum: 0.5923916324973106
typography_spectrum: 0.5791465216316283
title: Resilience Magazine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#47453f'
    - '#c3c2bd'
    - '#7a7468'
    - '#181818'
    - '#e0bf5c'
  brandStrength: 0.6456688395701349
  lightness: 0.31397981639020145
  saturation: 0.2596135011408478
  rhythmicContrast: 0.9965791192371398
purpose: []
