name: Resilience
favicon: null
layout_spectrum: 0.49491
typography_spectrum: 0.56189
title: Resilience Magazine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#685642'
    - '#b3a580'
    - '#ded29e'
    - '#b7c68b'
    - '#f4f0cb'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
