name: Resilience
favicon: null
layout_spectrum: 0.5923916324973106
typography_spectrum: 0.5791465216316283
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6456688395701349
  lightness: 0.31397981639020145
  saturation: 0.2596135011408478
  rhythmicContrast: 0.9965791192371398
purpose: []
