name: Resilience
favicon: null
layout_spectrum: 0.49491
typography_spectrum: 0.56189
title: Resilience Magazine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8b6bf'
    - '#c9d8c5'
    - '#7d4627'
    - '#927e73'
    - '#fdf8ed'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
