name: Resilience
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5791465216316283
title: Resilience Magazine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c1dad6'
    - '#6d929b'
    - '#b7afa3'
    - '#e8d0a9'
    - '#f5fafa'
  brandStrength: 0.6875
  lightness: 0.31397981639020145
  saturation: 0.2596135011408478
  rhythmicContrast: 0.9965791192371398
purpose: []
